# Generated by Django 4.2.2 on 2023-08-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_card', '0003_canvas_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas_data',
            name='canvas_adress',
            field=models.FileField(default=None, null=True, upload_to='base_desgin'),
        ),
    ]
