# Generated by Django 4.2.2 on 2023-08-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_card', '0004_alter_canvas_data_canvas_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas_data',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
    ]
