# Generated by Django 4.2.2 on 2023-08-03 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('id_card', '0005_alter_canvas_data_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canvas_data',
            old_name='full_name',
            new_name='current_user_id',
        ),
    ]
