# Generated by Django 4.2.2 on 2023-08-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_card', '0006_rename_full_name_canvas_data_current_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas_data',
            name='object_rank_location',
            field=models.CharField(default=None, max_length=600),
        ),
    ]
