# Generated by Django 4.2.2 on 2023-08-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_card', '0007_canvas_data_object_rank_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='generated_canvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.IntegerField()),
                ('pdf_adress', models.FileField(default=None, null=True, upload_to='generated/output')),
            ],
        ),
    ]
